=== VladislavGitHub1/XML/src/main/resources/xml/cards.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="Cards">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Card" type="Card" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="Card">
        <xsd:sequence>
            <xsd:element name="Thema" type="xsd:string" maxOccurs="unbounded"/>
            <xsd:element name="Type" type="xsd:string" maxOccurs="unbounded"/>
            <xsd:element name="Country" type="Country" maxOccurs="1"/>
            <xsd:element name="Year" type="xsd:gYear" maxOccurs="1"/>
            <xsd:element name="Author" type="Author" maxOccurs="unbounded"/>
            <xsd:element name="Valuable" maxOccurs="1"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:simpleType name="Country">
        <xsd:restriction>
            <xsd:enumeration value="Belarus"/>
            <xsd:enumeration value="USA"/>
            <xsd:enumeration value="Russia"/>
            <xsd:enumeration value="UK"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:complexType name="Author">
        <xsd:sequence>
            <xsd:element name="FirstName" type="xsd:string"/>
            <xsd:element name="LastName" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== VladislavGitHub1/XML/src/main/resources/xml/cards.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Cards xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="cards.xsd">
    <Card id="1">
        <Thema>CityScape</Thema>
        <Type>Congratulatory</Type>
        <Country>Belarus</Country>
        <Year>2023</Year>
        <Author>
            <FirstName>Ivan</FirstName>
            <LastName>Petrov</LastName>
        </Author>
        <Valuable>Thematic</Valuable>
    </Card>
    <Card id="2">
        <Thema>Nature</Thema>
        <Type>Congratulatory</Type>
        <Country>USA</Country>
        <Year>2023</Year>
        <Author>
            <FirstName>Oliver</FirstName>
            <LastName>Singer</LastName>
        </Author>
        <Valuable>Historical</Valuable>
    </Card>
</Cards>
